version: '3.9'
services:
    frontend:
        build: ./frontend
        volumes:
            - "./:/opt/app"
        ports:
            - "8000:8000"
    backend:
        build: ./backend
        volumes:
            - "./:/opt/app"
        ports:
            - "8040:8040"
            - "9229:9229"
    database:
        image: mongo:6.0
